[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/imoveis/:codigo"
  to = "/imoveis/:codigo"
  status = 200

[[redirects]]
  from = "/blog/:slug"
  to = "/blog/:slug"
  status = 200